"""empty message

Revision ID: 0d46524acfff
Revises: b864006ce1db
Create Date: 2018-12-01 21:38:26.802444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d46524acfff'
down_revision = 'b864006ce1db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'quartos', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quartos', type_='unique')
    # ### end Alembic commands ###
